In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import os

import tensorflow as tf
from tensorflow import keras

In [10]:
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()

train_labels = train_labels[:1000]
test_labels = test_labels[:1000]

train_images = train_images[:1000].reshape(-1, 28 * 28) / 255.0
test_images = test_images[:1000].reshape(-1, 28 * 28) / 255.0

print(train_images.shape, train_labels.shape,train_images.dtype, train_labels.dtype)

(1000, 784) (1000,) float64 uint8


In [102]:
class Model_Simple(tf.keras.Model):
    def __init__(self):
        super(Model_Simple, self).__init__()
        initializer = tf.initializers.GlorotUniform()
        regularizer = tf.keras.regularizers.l2(l=0.01)
        self.bn = tf.keras.layers.BatchNormalization(axis=1)
        self.fc1 = tf.keras.layers.Dense(200, activation='relu',
                                           kernel_initializer=initializer)
        # self.drop = tf.keras.layers.Dropout(0.2)
        self.fc2 = tf.keras.layers.Dense(10, activation="softmax"
                                         ,kernel_initializer=initializer)


    def call(self, input_tensor, training=False, show_bn=False):
        # print("is_training", training) # is_training 默认为false
        x = input_tensor
        x = self.bn(x, training)
        if show_bn:
            print("mean:",tf.math.reduce_mean(x, axis=0), "var:", tf.math.reduce_variance(x, axis=0))
        x = self.fc1(x)
        # x = self.drop(x, training)
        x = self.fc2(x)
       
        return x
# 创建一个基本的模型实例
model = Model_Simple()
model.compile(optimizer='adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'])
model(train_images[:1000], training=True, show_bn=True)
model.summary()

mean: tf.Tensor(
[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -8.76902717e-19 -3.61412289e-17
  0.00000000e+00  8.05466804e-17  2.08062734e-16  1.76067494e-16
 -1.49463775e-17  1.16087695e-17  1.70082698e-16  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.0000

In [105]:
model.fit(train_images, 
              train_labels,
              epochs=5, 
              validation_data=(test_images,test_labels),
              verbose=2)

Train on 1000 samples, validate on 1000 samples
Epoch 1/5
1000/1000 - 0s - loss: 0.0281 - accuracy: 0.9950 - val_loss: 0.4605 - val_accuracy: 0.8570
Epoch 2/5
1000/1000 - 0s - loss: 0.0234 - accuracy: 0.9990 - val_loss: 0.4484 - val_accuracy: 0.8610
Epoch 3/5
1000/1000 - 0s - loss: 0.0214 - accuracy: 0.9980 - val_loss: 0.4313 - val_accuracy: 0.8610
Epoch 4/5
1000/1000 - 0s - loss: 0.0106 - accuracy: 0.9990 - val_loss: 0.4564 - val_accuracy: 0.8620
Epoch 5/5
1000/1000 - 0s - loss: 0.0093 - accuracy: 1.0000 - val_loss: 0.4672 - val_accuracy: 0.8640


In [106]:
scores_call_train = model(train_images[:2],training=True)
print(scores_call_train[0],type(scores_call_train))
# model predict training 为False
scores_call_test = model(train_images[:2],training=False)
print(scores_call_test[0],type(scores_call_test))
scores_predict = model.predict(train_images[:2])
print(scores_predict[0],type(scores_predict))


tf.Tensor(
[5.78119836e-05 1.89361170e-03 4.01688743e-02 4.14712035e-01
 9.01040621e-03 4.25332918e-01 8.11007782e-03 3.24046194e-02
 5.82337104e-02 1.00759354e-02], shape=(10,), dtype=float64) <class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[9.95811838e-06 3.47859643e-06 8.51638351e-07 3.00310376e-03
 1.00916429e-08 9.96915368e-01 9.57947237e-08 4.69283478e-05
 2.00009403e-05 2.04589036e-07], shape=(10,), dtype=float64) <class 'tensorflow.python.framework.ops.EagerTensor'>
[9.95812142e-06 3.47859738e-06 8.51638672e-07 3.00310435e-03
 1.00916459e-08 9.96915368e-01 9.57947626e-08 4.69283621e-05
 2.00009446e-05 2.04589102e-07] <class 'numpy.ndarray'>
